# -*- coding: utf-8 -*-
"""
MyShortCut - UI 樣式與主題設定
"""

BG_COLOR = "#F4F6F9"
CARD_BG = "#FFFFFF"
PRIMARY_COLOR = "#1976D2"
PRIMARY_HOVER = "#1565C0"
TEXT_COLOR = "#212121"
TEXT_MUTED = "#666666"
BORDER_COLOR = "#E0E0E0"
ACCENT_COLOR = "#4CAF50"
DANGER_COLOR = "#E53935"

FONT_FAMILY = "Microsoft JhengHei UI"
FONT_TITLE = (FONT_FAMILY, 10, "bold")
FONT_LIST = (FONT_FAMILY, 9)
FONT_LIST_BOLD = (FONT_FAMILY, 9, "bold")
FONT_NORMAL = (FONT_FAMILY, 9)
FONT_BOLD = (FONT_FAMILY, 9, "bold")
FONT_SMALL = (FONT_FAMILY, 8)
FONT_BTN = (FONT_FAMILY, 9)